version: "3"

services:

  api:
    build: .
    restart: always
    command: "gunicorn main:app --bind 0.0.0.0:8000"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: "traefik:v2.9"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"



